class ConcurrencyParams:
    AMOUNT_OF_PROCESSES = 8

    FEATURE_ORDER_DISPATCHING_CONCURRENT = False
    FEATURE_ROUTE_CALCULATION_CONCURRENT = True
    FEATURE_BEST_ACTION_CALCULATION_CONCURRENT = False